---
- hosts: all
  connection: local
  vars:
    brew_repositories:
      - homebrew/dupes
      - homebrew/versions
      - caskroom/cask
    brew_packages:
      - ack
      - apple-gcc42
      - bash
      - brew-cask
      - coreutils
      - curl
      - direnv
      - ffmpeg
      - findutils
      - git
      - grep
      - htop-osx
      - hub
      - imagemagick
      - libxml2
      - libyaml
      - memcached
      - modules
      - ncdu
      - nmap
      - phantomjs
      - postgresql
      - rbenv
      - readline
      - redis
      - ruby-build
      - sqlite
      - tmux
      - tree
      - v8
      - vim
      - wget
      - docker
      - boot2docker
      - fig
    brew_cask_packages:
      - flash
      - google-chrome
      - java
      - quicklook-json
      - virtualbox
  tasks:
    - command: brew --env
      ignore_errors: True
      changed_when: False
      register: brew_installed

    - command: mktemp -d /tmp/brew.XXXXXX
      register: tempdir
      when: brew_installed|failed

    - get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest={{tempdir.stdout}}/brew.rb
      when: brew_installed|failed

    - name: install homebrew
      command: ruby {{tempdir.stdout}}/brew.rb
      when: brew_installed|failed

    - homebrew: update_homebrew=yes

    - command: brew tap {{item}}
      with_items: brew_repositories
      register: brew_tap
      changed_when: "'Warning: Already tapped!' not in brew_tap.stderr"

    - homebrew: name={{item}} state=present
      with_items: brew_packages

    - file: src=/usr/local/opt/{{item}}/homebrew.mxcl.{{item}}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{item}}.plist state=link force=yes
      with_items:
        - postgresql
        - redis
        - memcached

    - command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.{{item}}.plist
      with_items:
        - postgresql
        - redis
        - memcached

    - command: brew cask list
      register: installed_brew_cask_packages
      ignore_errors: True
      changed_when: False

    - command: brew cask install --appdir="/Applications" {{item}}
      with_items: brew_cask_packages
      when: item not in installed_brew_cask_packages.stdout

    # - copy: directory_mode="0700" src=home/ dest=~/ owner={{ansible_ssh_user}} group=staff mode="0600"

    - command: createuser -s -w postgres
    - postgresql_user: name=postgres role_attr_flags=SUPERUSER

    - name: setup boot2docker
      - command: boot2docker init
      - command: export DOCKER_HOST=tcp://192.168.59.103:2376
      - command: export DOCKER_CERT_PATH=/Users/mario/.boot2docker/certs/boot2docker-vm
      - command: export DOCKER_TLS_VERIFY=1


